#Get sensoren
GET http://localhost:3000/sensorvalues

###
#Get sensorvalues by ID
GET http://localhost:3000/sensorvalues/8


###
#einen sensor anlegen
POST http://localhost:3000/sensorvalues
content-type: application/json

{
    "sensorID": 100,
    "value": "17,32",
    
    "timestamp": "14.02.2022"
}

###
#Mehrere sensoren gleichzeitig anlegen
POST http://localhost:3000/sensorvalues
content-type: application/json

{
    "sensorValues": [
        {
            "sensorID": 100,
            "value": "19,32",
            "timestamp": "14.02.2022"
        },
        {
            "sensorID": 12,
            "value": "15,3",
            "timestamp": "14.02.2022"
        }
    ]
}

###
#delete sensor by id
DELETE http://localhost:3000/sensorvalues/13