#Get sensoren
GET http://localhost:3000/sensors

###
#Get sensors with type
GET http://localhost:3000/sensors/type/feuchtigkeitssensor

###
#Get sensor by ID
GET http://localhost:3000/sensors/13


###
#einen sensor anlegen
POST http://localhost:3000/sensors
content-type: application/json

{
    "fieldId": 1,
    "type": "temperatur",
    "locationOnField": "bottom"
}

###
#Mehrere sensoren gleichzeitig anlegen
POST http://localhost:3000/sensors
content-type: application/json

{
    "sensors": [
        {
            "fieldId": 3,
            "type": "temperatur",
            "locationOnField": "top left"
        },
        {
            "fieldId": 3,
            "type": "temperatur",
            "locationOnField": "middle left"
        },
        {
            "fieldId": 3,
            "type": "temperatur",
            "locationOnField": "middle right"
        }
    ]
}
###
#delete sensor by id
DELETE http://localhost:3000/sensors/13