#Get users
GET http://localhost:3000/users

###
#Get users with String contained in username, firstname, lastname, email
GET http://localhost:3000/users/name/testfdg

###
#Get user by ID
GET http://localhost:3000/users/70

###
#Einen user anlegen
POST http://localhost:3000/users
content-type: application/json

{
    "username": "oszi",
    "firstname": "Stefan",
    "lastname": "Ostojic",
    "email": "ossssszi@gmail.com",
    "password": "$2b$10$mduoe4DF8LxNr4K6y/lsmO2BsmeM2yMolxQIgffJvpySRCsRmSNy6",
    "role": "admin",
    "authToken": null
}

###
#mehrere user anlegen
POST http://localhost:3000/users
content-type: application/json

[
            {
                "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "testemsail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "tesasdemail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "testasddfemail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "tesasdfasdtemail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "testemasdfasfdail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Walti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "teasdfdfastemail@gmail.com",
                "role": "user",
                "authToken": null 
            },
            {
               "username": "Waalti",
                "firstname": "Walter",
                "lastname": "Kimmy",
                "password": "$2b$10$R5c0i9xb8Pq06GZUksulNuVNXC1/1S1sLjoKdIX454wrS50nnCvpi",
                "email": "testemasdfasdfail@gmail.com",
                "role": "user",
                "authToken": null 
            }   
    ]

###
#Delete user by id
DELETE http://localhost:3000/users/7
# token: "abrakadabra"

###
